sudo: true

language: java
jdk: oraclejdk8
services: postgresql

before_script:
  # Create the database.
  - psql -c "CREATE DATABASE bookforyou" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres'" -U postgres

  # Install the gradle project.
  - sudo add-apt-repository -y ppa:cwchien/gradle
  - sudo apt-get update
  - sudo apt-get install -y gradle


script:
  # Run the server project.
  - cd ./server
  # - gradle bootRun&

  # Run the server unit tests.
  - gradle test
