# the name of your JDBC driver
driverClass: org.postgresql.Driver

# the username
user: SpringBootUser

# the password
password: SpringBootPass

# the JDBC URL
url: jdbc:postgresql://127.0.0.1:5432/SpringBootRestApi

# any properties specific to your JDBC driver:
properties:
  charSet: UTF-8

# the maximum amount of time to wait on an empty pool before throwing an exception
maxWaitForConnection: 1

# the SQL query to run when validating a connection's liveness
validationQuery: "/* MyService Health Check */ SELECT 1"

# the minimum number of connections to keep open
minSize: 1

# the maximum number of connections to keep open
maxSize: 6

# whether or not idle connections should be validated
checkConnectionWhileIdle: false

# how long a connection must be held before it can be validated
checkConnectionHealthWhenIdleFor: 10

# the maximum lifetime of an idle connection
closeConnectionIfIdleFor: 60